# PagesCMS Configuration for CVAS Website

media:
  input: src/assets/images
  output: /assets/images

content:
  # Homepage
  - name: homepage
    label: Home Page
    path: src/index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: hero
        label: Hero Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: subtitle
            label: Subtitle
            type: string
          - name: description
            label: Description
            type: text
          - name: image
            label: Image
            type: image
          - name: cta
            label: CTA Button
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: link
                label: Link
                type: string
      - name: announcement
        label: Announcement Banner
        type: object
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: true
          - name: title
            label: Title
            type: string
          - name: image
            label: Image
            type: image
          - name: cta
            label: CTA Button
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: link
                label: Link
                type: string
      - name: adoption
        label: Adoption Section
        type: object
        fields:
          - name: enabled
            label: Enabled
            type: boolean
            default: true
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text
          - name: gridImage
            label: Grid Image
            type: image
          - name: cta
            label: CTA Button
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: link
                label: Link
                type: string
      - name: programs
        label: Programs Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: text
          - name: items
            label: Program Items
            type: object
            list: true
            fields:
              - name: title
                label: Title
                type: string
              - name: description
                label: Description
                type: text
              - name: link
                label: Link
                type: string
              - name: linkText
                label: Link Text
                type: string
              - name: enabled
                label: Enabled
                type: boolean
                default: true
      - name: waysToHelp
        label: Ways to Help Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: items
            label: Help Items
            type: object
            list: true
            fields:
              - name: title
                label: Title
                type: string
              - name: description
                label: Description
                type: text
              - name: actions
                label: Actions
                type: object
                list: true
                fields:
                  - name: text
                    label: Text
                    type: string
                  - name: link
                    label: Link
                    type: string
                  - name: type
                    label: Type
                    type: select
                    options:
                      values: [primary, secondary]
              - name: socialLinks
                label: Social Links
                type: object
                list: true
                fields:
                  - name: platform
                    label: Platform
                    type: string
                  - name: url
                    label: URL
                    type: string

  # Adopt Page
  - name: adopt
    label: Adopt Page
    path: src/content/pages/adopt.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        label: Permalink
        type: string
      - name: layout
        label: Layout
        type: string
        hidden: true
      - name: description
        label: Description
        type: text
      - name: hero
        label: Hero Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: collageImage
            label: Collage Image
            type: image
      - name: adoptContent
        label: Adopt Content
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: description
            label: Description
            type: markdown
      - name: petsSection
        label: Pets Section
        type: object
        fields:
          - name: title
            label: Title
            type: string
      - name: adoptionHours
        label: Adoption Hours
        type: object
        fields:
          - name: title
            label: Title
            type: string
      - name: adoptionProcess
        label: Adoption Process
        type: object
        fields:
          - name: title
            label: Title
            type: string
          - name: content
            label: Content
            type: markdown
          - name: links
            label: Links
            type: object
            list: true
            fields:
              - name: text
                label: Text
                type: string
              - name: url
                label: URL
                type: string
              - name: type
                label: Type
                type: select
                options:
                  values: [primary, secondary]