[build]
  command = "npm run build"
  publish = "_site"
  functions = "netlify/functions"

[dev]
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/petstablished"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"