siteTitle: Colville Valley Animal Sanctuary
siteDescription: CVAS's mission is to improve the quality of life for both pets and people by providing humane society services including shelter, rescue, spay/neuter, and adoption services.

socialLinks:
  facebook: https://facebook.com/cvasanctuary
  instagram: https://instagram.com/cvasanctuary
  tiktok: https://tiktok.com/@cvasanctuary

contactInfo:
  address: 501 Old Arden Hwy
  city: Colville
  state: WA
  zip: 99114
  phone: 509-684-1475
  email: office@cvasanctuary.org
  hours: By appointment only, Tuesday - Saturday, 10:00 AM - 3:00 PM

donations:
  catFee: $150
  dogFee: $250
  paymentMethods: We accept cash or credit/debit cards. No checks please.