backend:
  name: git-gateway
  branch: main

# Uncomment for local development
local_backend: true

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
              - label: "CTA Button"
                name: "cta"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
          - label: "Announcement Banner"
            name: "announcement"
            widget: "object"
            fields:
              - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - label: "CTA Button"
                name: "cta"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
          - label: "Adoption Section"
            name: "adoption"
            widget: "object"
            fields:
              - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Grid Image", name: "gridImage", widget: "image"}
              - label: "CTA Button"
                name: "cta"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "link", widget: "string"}
          - label: "Programs Section"
            name: "programs"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Program Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Link", name: "link", widget: "string"}
                  - {label: "Link Text", name: "linkText", widget: "string"}
                  - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
          - label: "Ways to Help Section"
            name: "waysToHelp"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Help Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - label: "Actions"
                    name: "actions"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "link", widget: "string"}
                      - {label: "Type", name: "type", widget: "select", options: ["primary", "secondary"]}
                  - label: "Social Links"
                    name: "socialLinks"
                    widget: "list"
                    required: false
                    fields:
                      - {label: "Platform", name: "platform", widget: "string"}
                      - {label: "URL", name: "url", widget: "string"}
      
      - label: "Adopt"
        name: "adopt"
        file: "src/content/pages/adopt.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Layout", name: "layout", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Collage Image", name: "collageImage", widget: "image"}
          - label: "Adopt Content"
            name: "adoptContent"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}
          - label: "Pets Section"
            name: "petsSection"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
          - label: "Adoption Hours"
            name: "adoptionHours"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
          - label: "Adoption Process"
            name: "adoptionProcess"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
              - label: "Links"
                name: "links"
                widget: "list"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
                  - {label: "Type", name: "type", widget: "select", options: ["primary", "secondary"]}
      
      - label: "About - Mission & Vision"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Impact"
        name: "impact"
        file: "src/content/pages/impact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Our Board"
        name: "board"
        file: "src/content/pages/board.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Board Members"
            name: "board_members"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Bio", name: "bio", widget: "text"}
              - {label: "Photo", name: "photo", widget: "image", required: false}
              - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Additional Content", name: "body", widget: "markdown", required: false}
      
      - label: "Resources"
        name: "resources"
        file: "src/content/pages/resources.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Hours", name: "hours", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "programs"
    label: "Programs"
    folder: "src/content/programs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "news"
    label: "News & Announcements"
    folder: "src/content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "eventDate", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "src/_data/settings.yml"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - label: "Social Links"
            name: "socialLinks"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "TikTok", name: "tiktok", widget: "string", required: false}
          - label: "Contact Info"
            name: "contactInfo"
            widget: "object"
            fields:
              - {label: "Address", name: "address", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "State", name: "state", widget: "string"}
              - {label: "Zip", name: "zip", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Hours", name: "hours", widget: "text"}
          - label: "Donation Settings"
            name: "donations"
            widget: "object"
            fields:
              - {label: "Cat/Kitten Fee", name: "catFee", widget: "string", default: "$150"}
              - {label: "Dog/Puppy Fee", name: "dogFee", widget: "string", default: "$250"}
              - {label: "Payment Methods", name: "paymentMethods", widget: "string", default: "Cash or credit/debit cards. No checks."}
      
      - label: "Newsletter"
        name: "newsletter"
        file: "src/_data/newsletter.yml"
        fields:
          - {label: "Enabled", name: "enabled", widget: "boolean", default: true}
          - {label: "Signup Text", name: "signupText", widget: "string", default: "Sign up for news and updates"}
          - {label: "Thank You Message", name: "thankYou", widget: "string", default: "Thank you for subscribing!"}